import { DBDocument, DocType } from "./DBDocument";
import { ChainReferencePurpose } from "./ChainReferencePurposeType";

/**
 * Represents a reference of an uploaded document to other chain objects. It contains some document metadata, in particular "purpose".
 */
export interface ChainFileReference extends DocType {
    /**
     * Storage key used for the document
     */
    documentId: string;
    /**
     * Object type. Possibilities are 'product', 'sku' or 'transaction'
     */
    objectType: string;
    /**
     * Id of the object of the object type.
     */
    objectId: string;
    /**
     * List of organization ids to which te document relates (maybe they are issuers, have to have copy?). Later we maybe add issuerOrganizations?
     */
    organizationIds: string[];
    /**
     * Describes a purpose (type) of a document in the value chain
     */
    purpose: ChainReferencePurpose;
    /**
     * Timestap of document added (should be autogenerated?)
     */
    timestamp?: string;
    /**
     * Document issue date.
     */
    issueDate?: string;
    /**
     * Document expiry date.
     */
    expiryDate?: string;
}

export class ChainFileReferenceDB extends DBDocument<ChainFileReference> {
    _prefix = "REF"
    docType = "file_reference"
}